spring:
  application:
    name: multiple-streams-processor
  cloud:
    stream:
      function: process
      bindings:
        process-in-0:
          destination: input-topic-1
        process-in-1:
          destination: input-topic-2
        process-out-0:
          destination: output-topic-1
        process-out-1:
          destination: output-topic-2
      kafka:
        streams:
          binder:
            application-id: processor-app
            configuration:
#              processing.guarantee: exactly_once
              commit.interval.ms: 1000
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            auto-create-topics: false
        binder:
          brokers: localhost:9092
